# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: train.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btrain.proto\"&\n\x12TrainStatusRequest\x12\x10\n\x08train_id\x18\x01 \x01(\x05\"b\n\x13TrainStatusResponse\x12\x10\n\x08train_id\x18\x01 \x01(\x05\x12\x10\n\x08location\x18\x02 \x01(\x01\x12\r\n\x05speed\x18\x03 \x01(\x01\x12\x18\n\x10\x64istance_to_stop\x18\x04 \x01(\x01\"G\n\x12TrainUpdateRequest\x12\x10\n\x08train_id\x18\x01 \x01(\x05\x12\x10\n\x08location\x18\x02 \x01(\x01\x12\r\n\x05speed\x18\x03 \x01(\x01\"&\n\x13TrainUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x8c\x01\n\tScheduler\x12=\n\x0eGetTrainStatus\x12\x13.TrainStatusRequest\x1a\x14.TrainStatusResponse\"\x00\x12@\n\x11UpdateTrainStatus\x12\x13.TrainUpdateRequest\x1a\x14.TrainUpdateResponse\"\x00\x62\x06proto3')



_TRAINSTATUSREQUEST = DESCRIPTOR.message_types_by_name['TrainStatusRequest']
_TRAINSTATUSRESPONSE = DESCRIPTOR.message_types_by_name['TrainStatusResponse']
_TRAINUPDATEREQUEST = DESCRIPTOR.message_types_by_name['TrainUpdateRequest']
_TRAINUPDATERESPONSE = DESCRIPTOR.message_types_by_name['TrainUpdateResponse']
TrainStatusRequest = _reflection.GeneratedProtocolMessageType('TrainStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRAINSTATUSREQUEST,
  '__module__' : 'train_pb2'
  # @@protoc_insertion_point(class_scope:TrainStatusRequest)
  })
_sym_db.RegisterMessage(TrainStatusRequest)

TrainStatusResponse = _reflection.GeneratedProtocolMessageType('TrainStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINSTATUSRESPONSE,
  '__module__' : 'train_pb2'
  # @@protoc_insertion_point(class_scope:TrainStatusResponse)
  })
_sym_db.RegisterMessage(TrainStatusResponse)

TrainUpdateRequest = _reflection.GeneratedProtocolMessageType('TrainUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRAINUPDATEREQUEST,
  '__module__' : 'train_pb2'
  # @@protoc_insertion_point(class_scope:TrainUpdateRequest)
  })
_sym_db.RegisterMessage(TrainUpdateRequest)

TrainUpdateResponse = _reflection.GeneratedProtocolMessageType('TrainUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINUPDATERESPONSE,
  '__module__' : 'train_pb2'
  # @@protoc_insertion_point(class_scope:TrainUpdateResponse)
  })
_sym_db.RegisterMessage(TrainUpdateResponse)

_SCHEDULER = DESCRIPTOR.services_by_name['Scheduler']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRAINSTATUSREQUEST._serialized_start=15
  _TRAINSTATUSREQUEST._serialized_end=53
  _TRAINSTATUSRESPONSE._serialized_start=55
  _TRAINSTATUSRESPONSE._serialized_end=153
  _TRAINUPDATEREQUEST._serialized_start=155
  _TRAINUPDATEREQUEST._serialized_end=226
  _TRAINUPDATERESPONSE._serialized_start=228
  _TRAINUPDATERESPONSE._serialized_end=266
  _SCHEDULER._serialized_start=269
  _SCHEDULER._serialized_end=409
# @@protoc_insertion_point(module_scope)
