# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alarm_sensor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61larm_sensor.proto\"\x07\n\x05\x45mpty\"1\n\x04\x44\x61ta\x12\x10\n\x08pir_data\x18\x01 \x01(\x05\x12\x17\n\x0fultrasonic_data\x18\x02 \x01(\x05\x32*\n\x0b\x41larmSensor\x12\x1b\n\x08SendData\x12\x05.Data\x1a\x06.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alarm_sensor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=22
  _EMPTY._serialized_end=29
  _DATA._serialized_start=31
  _DATA._serialized_end=80
  _ALARMSENSOR._serialized_start=82
  _ALARMSENSOR._serialized_end=124
# @@protoc_insertion_point(module_scope)
